import { generateRandomNumber } from "./generateRandomNumber";

const firstNamesMoked = [
  "Emma",
  "Olivia",
  "Aiden",
  "Sophia",
  "Liam",
  "Mia",
  "Lucas",
  "Isabella",
  "Jackson",
  "Oliver",
  "Ava",
  "Logan",
  "Sophie",
  "Lily",
  "Ethan",
  "Ella",
  "Mason",
  "Grace",
  "Madison",
  "Aiden",
  "Carter",
  "Chloe",
  "Liam",
  "Zoe",
  "Avery",
  "Nora",
  "Henry",
  "Scarlett",
  "Leo",
  "Amelia",
  "Elijah",
  "Abigail",
  "Caleb",
  "Hannah",
  "Benjamin",
  "Evelyn",
  "James",
  "Aria",
  "Michael",
  "Addison",
  "Daniel",
  "Ellie",
  "Matthew",
  "Aubrey",
  "Samuel",
  "Stella",
  "Joseph",
  "Natalie",
  "David",
  "Sofia",
  "Dylan",
  "Victoria",
  "Gabriel",
  "Zoe",
  "Joshua",
  "Brooklyn",
  "Andrew",
  "Paisley",
  "Julian",
  "Lillian",
  "Christopher",
  "Lucy",
  "Isaac",
  "Anna",
  "John",
  "Katherine",
  "Lincoln",
  "Bella",
  "Nathan",
  "Hazel",
  "Ryan",
  "Leah",
  "Wyatt",
  "Willow",
  "Sebastian",
  "Grace",
  "Eli",
  "Aurora",
  "Levi",
  "Audrey",
  "Nicholas",
  "Nova",
  "Ava",
  "Piper",
  "Cameron",
  "Aaliyah",
  "Christian",
  "Ellie",
  "Olivia",
  "Ruby",
];

const lastNamesMoked = [
  "Smith",
  "Johnson",
  "Williams",
  "Jones",
  "Brown",
  "Davis",
  "Miller",
  "Wilson",
  "Moore",
  "Taylor",
  "Anderson",
  "Thomas",
  "Jackson",
  "White",
  "Harris",
  "Martin",
  "Thompson",
  "Garcia",
  "Martinez",
  "Robinson",
  "Clark",
  "Rodriguez",
  "Lewis",
  "Lee",
  "Walker",
  "Hall",
  "Allen",
  "Young",
  "Hernandez",
  "King",
  "Wright",
  "Lopez",
  "Hill",
  "Scott",
  "Green",
  "Adams",
  "Baker",
  "Gonzalez",
  "Nelson",
  "Carter",
  "Mitchell",
  "Perez",
  "Roberts",
  "Turner",
  "Phillips",
  "Campbell",
  "Parker",
  "Evans",
  "Edwards",
  "Collins",
  "Stewart",
  "Sanchez",
  "Morris",
  "Rogers",
  "Reed",
  "Cook",
  "Morgan",
  "Bell",
  "Murphy",
  "Bailey",
  "Rivera",
  "Cooper",
  "Richardson",
  "Cox",
  "Howard",
  "Ward",
  "Torres",
  "Peterson",
  "Gray",
  "Ramirez",
  "James",
  "Watson",
  "Brooks",
  "Kelly",
  "Sanders",
  "Price",
  "Bennett",
  "Wood",
  "Barnes",
  "Ross",
  "Henderson",
  "Coleman",
  "Jenkins",
  "Perry",
  "Powell",
  "Long",
  "Patterson",
  "Hughes",
  "Flores",
  "Washington",
];

export function generateRandomFirstName() {
  const randomFirstName =
    firstNamesMoked[generateRandomNumber(firstNamesMoked.length)];

  return randomFirstName;
}

export function generateRandomLastName() {
  const randomLastName =
    lastNamesMoked[generateRandomNumber(lastNamesMoked.length)];

  return randomLastName;
}

export function generateFullName() {
  const randomFirstName = generateRandomFirstName();
  const randomLastName = generateRandomLastName();

  return randomFirstName + " " + randomLastName;
}
