export enum AppRoutes {
  HOME = "/",
  LOGIN = "/login",
  CREATE_ACCOUNT = "/create-account",
  CLASS = "/class",
  CLASS_DASHBOARD = "/class/dashboard",
  CLASS_PROFILE = "/class/profile",
  CLASS_COURSES = "/class/courses",
  CLASS_COURSE = "/class/course/:courseSlug/:moduleSlug/:lessonSlug",
  CLASS_CERTIFICATE = "/class/cerificates",
  CLASS_CERTIFICATE_VALIDATOR = "/class/cerificate/:courseId",
  LOGOFF = "/class/logoff",
  TERMS_OF_USE = "/terms-of-use",
  POLICY_PRIVACY = "/polic",
}
