export enum AppRoutes {
  HOME = "/",
  SIGN_IN = "/signIn",
  SIGN_UP = "/signUp",
  SIGN_OUT = "/signOut",
  CLASS = "/class",
  CLASS_DASHBOARD = "/class/dashboard",
  CLASS_PROFILE = "/class/profile",
  CLASS_COURSES = "/class/courses",
  CLASS_COURSE = "/class/course/:courseSlug/:moduleSlug/:lessonSlug",
  CLASS_FINANCES = "/class/finances",
  CLASS_CERTIFICATE = "/class/cerificates",
  CLASS_CERTIFICATE_VALIDATOR = "/class/cerificate/:courseId",
  TERMS_OF_USE = "/terms-of-use",
  POLICY_PRIVACY = "/polic",
}
