import "./fade";
import "./zoom";
import "./rotate";
import "./slide";
import "./textAnimations";
import "./blur";

export type Animations =
  | "fadeIn"
  | "fadeOut"
  | "fadeInUp"
  | "fadeOutUp"
  | "fadeInDown"
  | "fadeOutDown"
  | "fadeInLeft"
  | "fadeOutLeft"
  | "fadeInRight"
  | "fadeOutRight"
  | "zoomIn"
  | "zoomOut"
  | "rotateIn"
  | "rotateOut"
  | "slideInUp"
  | "slideOutUp"
  | "slideInDown"
  | "slideOutDown"
  | "slideInLeft"
  | "slideOutLeft"
  | "slideInRight"
  | "slideOutRight"
  | "typewriter"
  | "blurIn"
  | "blurOut";
